---
deployment:
  tasks:
    - /bin/mkdir -p /home/learning/easyai.com.au/github
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' /home/learning/repositories/test1/ /home/learning/easyai.com.au/github/
    - /bin/date > /home/learning/easyai.com.au/github/DEPLOY_WORKED.txt
    - /bin/ls -la /home/learning/easyai.com.au/github/ > /home/learning/easyai.com.au/github/DEPLOY_LISTING.txt
